version: '3.8'
services:
  words-dev:
    image: ghcr.io/cache8063/words:develop
    container_name: words-dev
    ports:
      - "3333:80"
    environment:
      - NODE_ENV=development
      - PORT=80
      - LISTEN_ADDRESS=0.0.0.0
    env_file:
      - .env.development
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.words-dev.rule=Host(`words-dev.yourdomain.com`)"
      - "traefik.http.services.words-dev.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true