version: '3.8'

services:
  words:
    image: ghcr.io/cache8063/words:latest
    ports:
      - "8086:80"
    environment:
      - NODE_ENV=production
      - LISTEN_ADDRESS=0.0.0.0
      - PORT=80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "app=words"
      - "version=latest"
