services:
  words:
    image: ghcr.io/cache8063/words:develop
    ports:
      - "8086:80"
    environment:
      - NODE_ENV=production
      - LISTEN_ADDRESS=0.0.0.0
      - PORT=80
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    labels:
      - "app=words"
      - "version=develop"