version: '3.8'

services:
  words:
    image: words:v2-themes
    ports:
      - "8086:80"
    environment:
      - NODE_ENV=production
      - LISTEN_ADDRESS=0.0.0.0
      - PORT=80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    labels:
      - "app=words"
      - "version=v2-themes"