services:
  words:
    image: ghcr.io/cache8063/words:latest
    ports:
      - "8086:80"
    environment:
      - NODE_ENV=production
      - LISTEN_ADDRESS=0.0.0.0
      - PORT=80
    restart: unless-stopped
    labels:
      - "app=words"
      - "version=v2-themes"