version: '3.8'
services:
  words:
    image: ghcr.io/cache8063/words:develop
    container_name: words-game
    ports:
      - "8086:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - LISTEN_ADDRESS=0.0.0.0
    restart: unless-stopped